#! /bin/bash
# Requires ImageMagick, Xdialog

IFS=$(echo -en "\n\b")

Xdialog --inputbox "Input Percentage" 10 40 2>/tmp/resizemagick.perc.tmp
percentage=`cat /tmp/resizemagick.perc.tmp`
rm /tmp/resizemagick.perc.tmp
percentage="${percentage//'%'}"

if [ -z $percentage ]; then
        exit
fi

for var in $CAJA_SCRIPT_SELECTED_FILE_PATHS; do
    filename=$(basename "$var")
    extension="${filename##*.}"
    filenameNoExtension="${filename%.*}"

    convert "$filename" -resize "$percentage"% "$filenameNoExtension resized.$extension"
done
